### ISSUE TITLE
Display nicer message if links configuration is invalid in pipeline's spec

### ISSUE THREAD

**Issue by mspanc** [membraneframework/membrane-core#26]
The current message is not really self-explanatory if you're pointing to a non-existent element while declaring links for pipeline spec.

 ```
* (EXIT from #PID<0.470.0>) shell process exited with reason: an exception was raised:
    ** (WithClauseError) no with clause matching: {{:error, {:resolve_link, %{element: :seeker, pad: :sink}, {:unknown_child, :seeker}}}, %Membrane.Pipeline.State{children_ids: %{}, children_to_pids: %{mad: #PID<0.474.0>, parser: #PID<0.475.0>, peakmeter: #PID<0.476.0>, sink: #PID<0.477.0>, source: #PID<0.478.0>}, internal_state: %{}, module: Twist.AutoAudioTrim.Trimmer.Pipeline, pending_pids: nil, pids_to_children: %{#PID<0.474.0> => :mad, #PID<0.475.0> => :parser, #PID<0.476.0> => :peakmeter, #PID<0.477.0> => :sink, #PID<0.478.0> => :source}, playback: %Membrane.Mixins.Playback{async_state_change: false, pending_state: nil, state: :stopped, target_locked?: false, target_state: :stopped}, terminating?: false}}
        (membrane_core) lib/membrane_core/pipeline.ex:192: Membrane.Pipeline.handle_spec/2
        (membrane_core) lib/membrane_core/pipeline.ex:451: Membrane.Pipeline.handle_info/2
        (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3

Interactive Elixir (1.6.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(2)>
22:54:26.922 [error] GenServer #PID<0.472.0> terminating
** (WithClauseError) no with clause matching: {{:error, {:resolve_link, %{element: :seeker, pad: :sink}, {:unknown_child, :seeker}}}, %Membrane.Pipeline.State{children_ids: %{}, children_to_pids: %{mad: #PID<0.474.0>, parser: #PID<0.475.0>, peakmeter: #PID<0.476.0>, sink: #PID<0.477.0>, source: #PID<0.478.0>}, internal_state: %{}, module: Twist.AutoAudioTrim.Trimmer.Pipeline, pending_pids: nil, pids_to_children: %{#PID<0.474.0> => :mad, #PID<0.475.0> => :parser, #PID<0.476.0> => :peakmeter, #PID<0.477.0> => :sink, #PID<0.478.0> => :source}, playback: %Membrane.Mixins.Playback{async_state_change: false, pending_state: nil, state: :stopped, target_locked?: false, target_state: :stopped}, terminating?: false}}
    (membrane_core) lib/membrane_core/pipeline.ex:192: Membrane.Pipeline.handle_spec/2
    (membrane_core) lib/membrane_core/pipeline.ex:451: Membrane.Pipeline.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: [:membrane_pipeline_spec, %Membrane.Pipeline.Spec{children: %{mad: Membrane.Element.Mad.Decoder, parser: Membrane.Element.MPEGAudioParse.Parser, peakmeter: {Membrane.Element.Audiometer.Peakmeter, %Membrane.Element.Audiometer.Peakmeter.Options{period: 100}}, sink: Membrane.Element.Fake.Sink.Bytes, source: {Membrane.Element.HTTPoison.Source, %Membrane.Element.HTTPoison.Source.Options{body: "", headers: [Connection: "keep-alive", Accept: "audio/mpeg", "User-Agent": "RadioKit Twist: AutoAudioTrim"], location: "http://localhost:8000/variant.mp3", method: :get, options: nil}}}, links: %{{:mad, :source} => {:seeker, :sink, [pull_buffer: [preferred_size: 30000]]}, {:parser, :source} => {:mad, :sink, [pull_buffer: [preferred_size: 30000]]}, {:peakmeter, :source} => {:sink, :sink, [pull_buffer: [preferred_size: 30000]]}, {:source, :source} => {:parser, :sink, [pull_buffer: [preferred_size: 30000]]}}}]
State: %Membrane.Pipeline.State{children_ids: %{}, children_to_pids: %{}, internal_state: %{}, module: Twist.AutoAudioTrim.Trimmer.Pipeline, pending_pids: nil, pids_to_children: %{}, playback: %Membrane.Mixins.Playback{async_state_change: false, pending_state: nil, state: :stopped, target_locked?: false, target_state: :stopped}, terminating?: false}
```

**Comment by mspanc** [comment]
According to the planning meeting on 25.06.2018 it is not urgent.
